spring.datasource:
  url: jdbc:oracle:thin:@host:port:service
  username: ******
  password: ******

camunda.bpm:
  filter.create: All Tasks
  authorization:
    enabled: true
  admin-user:
    id: demo
    password: demo
